spring:
  application:
    name: weather-app

server:
  port: 8080

weather:
  api:
    key: 66daf58f96a0953a1ea2fd4b2efbb549
    base-url: https://api.openweathermap.org/data/2.5

springdoc:
  swagger-ui:
    path: /swagger-ui.html